const mockDoneRecipes = [
  { id: 52977,
    type: 'meal',
    nationality: 'Turkish',
    category: 'Side',
    alcoholicOrNot: '',
    name: 'Corba',
    image: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
    doneDate: '01/01/2022',
    tags: ['Soup'],
  },
  { id: 53060,
    type: 'meal',
    nationality: 'Croatian',
    category: 'Side',
    alcoholicOrNot: '',
    name: 'Burek',
    image: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
    doneDate: '02/02/2022',
    tags: ['treetfood', 'Onthego'],
  },
  { id: 15997,
    type: 'drink',
    nationality: '',
    category: 'Ordinary Drink',
    alcoholicOrNot: 'Optional alcohol',
    name: 'GG',
    image: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
    doneDate: '03/03/2022',
    tags: [],
  },
];

export default mockDoneRecipes;
